// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paizvyddpliawmtrhkmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhaXp2eWRkcGxpYXdtdHJoa21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjE3NTksImV4cCI6MjA2MTYzNzc1OX0.uKn8gH-8yeiotWtcepSQekwcXp2aFNiTPTkhtiX8Fsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);